"""UI基本設計に合わせたView専用の色と寸法を定義する。"""

from typing import Self

from forest.shared import Constants


class ViewTheme:
    WINDOW_BACKGROUND = "#FFFFFF"
    CANVAS_BACKGROUND = "#FFFFFF"
    GRID_COLOR = "#D9D9D7"
    EDGE_COLOR = "#C5C5C2"
    TEXT_COLOR = "#37352F"
    SECONDARY_TEXT_COLOR = "#787774"
    MUTED_TEXT_COLOR = "#9B9A97"
    ROOT_FILL_COLOR = "#FAF5F0"
    ROOT_BORDER_COLOR = "#E6D9CE"
    NODE_FILL_COLOR = "#FBFAF8"
    NODE_BORDER_COLOR = "#E5E1DC"
    LEAF_FILL_COLOR = "#F6FAF4"
    LEAF_BORDER_COLOR = "#DCE8D8"
    ROOT_SELECTED_FILL_COLOR = Constants.ROOT_SELECTED_FILL_COLOR
    ROOT_SELECTED_BORDER_COLOR = Constants.ROOT_SELECTED_BORDER_COLOR
    NODE_SELECTED_FILL_COLOR = Constants.NODE_SELECTED_FILL_COLOR
    NODE_SELECTED_BORDER_COLOR = Constants.NODE_SELECTED_BORDER_COLOR
    LEAF_SELECTED_FILL_COLOR = Constants.LEAF_SELECTED_FILL_COLOR
    LEAF_SELECTED_BORDER_COLOR = Constants.LEAF_SELECTED_BORDER_COLOR
    POPOVER_BACKGROUND = "#FFFFFF"
    POPOVER_BORDER_COLOR = "#DFDFDD"
    SEPARATOR_COLOR = "#E8E8E6"
    CONTROL_BACKGROUND = "#FCFCFB"
    GRID_SPACING = 20
    GRID_DOT_RADIUS = 1
    NODE_CORNER_RADIUS = 4
    POPOVER_WIDTH = 246
    NODE_POPOVER_HEIGHT = 154
    CANVAS_POPOVER_HEIGHT = 190
    PLAYBACK_WIDTH = 126
    PLAYBACK_HEIGHT = 42

    def __new__(cls) -> Self:
        raise TypeError("ViewTheme cannot be instantiated")
