"""ControllerからModelへ送信できる更新メッセージを定義する。"""

from pathlib import Path
from typing import Protocol

from forest.shared import BBox, Point
from forest.tree import BaseNode


class ModelCommandPort(Protocol):
    """Controllerが利用するModel更新操作だけを公開する受信口。"""

    def loadFile(self, inputPath: Path) -> None: ...

    def selectNode(self, node: BaseNode, popupBBox: BBox) -> None: ...

    def clearSelection(self) -> None: ...

    def clearTree(self) -> None: ...

    def renameSelectedNode(self, text: str) -> None: ...

    def showStep(self, index: int) -> None: ...

    def showPreviousStep(self) -> None: ...

    def showNextStep(self) -> None: ...

    def setPlaying(self, isPlaying: bool) -> None: ...

    def exportCanvas(self, outputPath: Path) -> None: ...

    def exportSelectedSubgraph(self, outputPath: Path) -> None: ...

    def resizeDesktop(self, width: float, height: float) -> None: ...

    def panDesktop(self, dx: float, dy: float) -> None: ...

    def zoomDesktopAt(self, anchor: Point, scaleDelta: float) -> None: ...

    def resetDesktopViewport(self) -> None: ...
