[project]
name = "forest-program"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.14"
dependencies = [
    "pillow>=12.3.0",
    "pyside6>=6.11.1",
]

[dependency-groups]
dev = ["pyinstaller>=6.21.0", "pytest>=9.1.1", "ruff>=0.16.1", "ty>=0.0.65"]


[tool.ruff]
line-length = 120
